# Generated by Django 5.2.5 on 2025-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminuser_managers_alter_adminuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
